//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProLaminator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProLaminator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 贴膜定位检测视觉系统.
        /// </summary>
        internal static string chs_APPNAME {
            get {
                return ResourceManager.GetString("chs_APPNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 软件信息.
        /// </summary>
        internal static string chs_BBI_APPINFO {
            get {
                return ResourceManager.GetString("chs_BBI_APPINFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 退出.
        /// </summary>
        internal static string chs_BBI_EXITSYSTEM {
            get {
                return ResourceManager.GetString("chs_BBI_EXITSYSTEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 加载.
        /// </summary>
        internal static string chs_BBI_LOADROUTINE {
            get {
                return ResourceManager.GetString("chs_BBI_LOADROUTINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 登录.
        /// </summary>
        internal static string chs_BBI_LOGIN {
            get {
                return ResourceManager.GetString("chs_BBI_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 登出.
        /// </summary>
        internal static string chs_BBI_LOGOUT {
            get {
                return ResourceManager.GetString("chs_BBI_LOGOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 管理.
        /// </summary>
        internal static string chs_BBI_MANAGEACCOUNT {
            get {
                return ResourceManager.GetString("chs_BBI_MANAGEACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 管理.
        /// </summary>
        internal static string chs_BBI_MANAGEROUTINE {
            get {
                return ResourceManager.GetString("chs_BBI_MANAGEROUTINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新建.
        /// </summary>
        internal static string chs_BBI_NEWROUTINE {
            get {
                return ResourceManager.GetString("chs_BBI_NEWROUTINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 运行.
        /// </summary>
        internal static string chs_BBI_RUNCONTINUE {
            get {
                return ResourceManager.GetString("chs_BBI_RUNCONTINUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 测试.
        /// </summary>
        internal static string chs_BBI_RUNONCE {
            get {
                return ResourceManager.GetString("chs_BBI_RUNONCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 停止.
        /// </summary>
        internal static string chs_BBI_RUNSTOP {
            get {
                return ResourceManager.GetString("chs_BBI_RUNSTOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 运控.
        /// </summary>
        internal static string chs_BBI_SETMOTION {
            get {
                return ResourceManager.GetString("chs_BBI_SETMOTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 程式.
        /// </summary>
        internal static string chs_BBI_SETROUTINE {
            get {
                return ResourceManager.GetString("chs_BBI_SETROUTINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 系统.
        /// </summary>
        internal static string chs_BBI_SETSYSTEM {
            get {
                return ResourceManager.GetString("chs_BBI_SETSYSTEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 厂商信息.
        /// </summary>
        internal static string chs_BBI_VENDORINFO {
            get {
                return ResourceManager.GetString("chs_BBI_VENDORINFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当前程式.
        /// </summary>
        internal static string chs_BEI_CURRENTROUTINE {
            get {
                return ResourceManager.GetString("chs_BEI_CURRENTROUTINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关于.
        /// </summary>
        internal static string chs_BSBI_ABOUT {
            get {
                return ResourceManager.GetString("chs_BSBI_ABOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 账户.
        /// </summary>
        internal static string chs_BSBI_ACCOUNT {
            get {
                return ResourceManager.GetString("chs_BSBI_ACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 板卡状态.
        /// </summary>
        internal static string chs_BSBI_BOARDSTATUS {
            get {
                return ResourceManager.GetString("chs_BSBI_BOARDSTATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 相机状态.
        /// </summary>
        internal static string chs_BSBI_CAMERASTATUS {
            get {
                return ResourceManager.GetString("chs_BSBI_CAMERASTATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 程式.
        /// </summary>
        internal static string chs_BSBI_ROUTINE {
            get {
                return ResourceManager.GetString("chs_BSBI_ROUTINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 串口状态.
        /// </summary>
        internal static string chs_BSBI_SERIALPORTSTATUS {
            get {
                return ResourceManager.GetString("chs_BSBI_SERIALPORTSTATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置.
        /// </summary>
        internal static string chs_BSBI_SET {
            get {
                return ResourceManager.GetString("chs_BSBI_SET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;&gt;.
        /// </summary>
        internal static string chs_BSTI_CLIENTNAME {
            get {
                return ResourceManager.GetString("chs_BSTI_CLIENTNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当前账户:.
        /// </summary>
        internal static string chs_BSTI_CURRENTACCOUNT {
            get {
                return ResourceManager.GetString("chs_BSTI_CURRENTACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当前时间:.
        /// </summary>
        internal static string chs_BSTI_CURRENTTIME {
            get {
                return ResourceManager.GetString("chs_BSTI_CURRENTTIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新建程式对话框.
        /// </summary>
        internal static string chs_FRM_NEWROUTINE {
            get {
                return ResourceManager.GetString("chs_FRM_NEWROUTINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 程式管理对话框.
        /// </summary>
        internal static string chs_FRM_ROUTINEMANAGER {
            get {
                return ResourceManager.GetString("chs_FRM_ROUTINEMANAGER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置程式参数.
        /// </summary>
        internal static string chs_FRM_SETROUTINEPARA {
            get {
                return ResourceManager.GetString("chs_FRM_SETROUTINEPARA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 耗时:.
        /// </summary>
        internal static string chs_LBLC_ELAPSETIME {
            get {
                return ResourceManager.GetString("chs_LBLC_ELAPSETIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请输入新程式的名称：.
        /// </summary>
        internal static string chs_LBLC_PROMPTNEWROUTINENAME {
            get {
                return ResourceManager.GetString("chs_LBLC_PROMPTNEWROUTINENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 次品:.
        /// </summary>
        internal static string chs_LBLC_PRONG {
            get {
                return ResourceManager.GetString("chs_LBLC_PRONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 良品:.
        /// </summary>
        internal static string chs_LBLC_PROOK {
            get {
                return ResourceManager.GetString("chs_LBLC_PROOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 良率:.
        /// </summary>
        internal static string chs_LBLC_PROYIELDRATIO {
            get {
                return ResourceManager.GetString("chs_LBLC_PROYIELDRATIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 停止.
        /// </summary>
        internal static string chs_LBLC_RUNSTATE {
            get {
                return ResourceManager.GetString("chs_LBLC_RUNSTATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 按名称搜索:.
        /// </summary>
        internal static string chs_LBLC_SEARCHBYNAMES {
            get {
                return ResourceManager.GetString("chs_LBLC_SEARCHBYNAMES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 离线.
        /// </summary>
        internal static string chs_OFFLINE {
            get {
                return ResourceManager.GetString("chs_OFFLINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 在线.
        /// </summary>
        internal static string chs_ONLINE {
            get {
                return ResourceManager.GetString("chs_ONLINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取消.
        /// </summary>
        internal static string chs_SBTN_CANCEL {
            get {
                return ResourceManager.GetString("chs_SBTN_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 清空.
        /// </summary>
        internal static string chs_SBTN_CLEARROUTINE {
            get {
                return ResourceManager.GetString("chs_SBTN_CLEARROUTINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确认.
        /// </summary>
        internal static string chs_SBTN_CONFIRM {
            get {
                return ResourceManager.GetString("chs_SBTN_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 清零.
        /// </summary>
        internal static string chs_SBTN_COUNTCLEAR {
            get {
                return ResourceManager.GetString("chs_SBTN_COUNTCLEAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除.
        /// </summary>
        internal static string chs_SBTN_DELETEROUTINE {
            get {
                return ResourceManager.GetString("chs_SBTN_DELETEROUTINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 编辑.
        /// </summary>
        internal static string chs_SBTN_EDITROUTINE {
            get {
                return ResourceManager.GetString("chs_SBTN_EDITROUTINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 退出.
        /// </summary>
        internal static string chs_SBTN_EXIT {
            get {
                return ResourceManager.GetString("chs_SBTN_EXIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 加载.
        /// </summary>
        internal static string chs_SBTN_LOADROUTINE {
            get {
                return ResourceManager.GetString("chs_SBTN_LOADROUTINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新建.
        /// </summary>
        internal static string chs_SBTN_NEWROUTINE {
            get {
                return ResourceManager.GetString("chs_SBTN_NEWROUTINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 搜索.
        /// </summary>
        internal static string chs_SBTN_SEARCH {
            get {
                return ResourceManager.GetString("chs_SBTN_SEARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 深圳市汇众智慧科技有限公司.
        /// </summary>
        internal static string chs_VENDORINFO {
            get {
                return ResourceManager.GetString("chs_VENDORINFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laminator Inspection Vision System.
        /// </summary>
        internal static string en_APPNAME {
            get {
                return ResourceManager.GetString("en_APPNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Info.
        /// </summary>
        internal static string en_BBI_APPINFO {
            get {
                return ResourceManager.GetString("en_BBI_APPINFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string en_BBI_EXITSYSTEM {
            get {
                return ResourceManager.GetString("en_BBI_EXITSYSTEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        internal static string en_BBI_LOADROUTINE {
            get {
                return ResourceManager.GetString("en_BBI_LOADROUTINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogIn.
        /// </summary>
        internal static string en_BBI_LOGIN {
            get {
                return ResourceManager.GetString("en_BBI_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogOut.
        /// </summary>
        internal static string en_BBI_LOGOUT {
            get {
                return ResourceManager.GetString("en_BBI_LOGOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage.
        /// </summary>
        internal static string en_BBI_MANAGEACCOUNT {
            get {
                return ResourceManager.GetString("en_BBI_MANAGEACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage.
        /// </summary>
        internal static string en_BBI_MANAGEROUTINE {
            get {
                return ResourceManager.GetString("en_BBI_MANAGEROUTINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string en_BBI_NEWROUTINE {
            get {
                return ResourceManager.GetString("en_BBI_NEWROUTINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run.
        /// </summary>
        internal static string en_BBI_RUNCONTINUE {
            get {
                return ResourceManager.GetString("en_BBI_RUNCONTINUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        internal static string en_BBI_RUNONCE {
            get {
                return ResourceManager.GetString("en_BBI_RUNONCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string en_BBI_RUNSTOP {
            get {
                return ResourceManager.GetString("en_BBI_RUNSTOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motion.
        /// </summary>
        internal static string en_BBI_SETMOTION {
            get {
                return ResourceManager.GetString("en_BBI_SETMOTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Routine.
        /// </summary>
        internal static string en_BBI_SETROUTINE {
            get {
                return ResourceManager.GetString("en_BBI_SETROUTINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        internal static string en_BBI_SETSYSTEM {
            get {
                return ResourceManager.GetString("en_BBI_SETSYSTEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor Info.
        /// </summary>
        internal static string en_BBI_VENDORINFO {
            get {
                return ResourceManager.GetString("en_BBI_VENDORINFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CurrentRoutine.
        /// </summary>
        internal static string en_BEI_CURRENTROUTINE {
            get {
                return ResourceManager.GetString("en_BEI_CURRENTROUTINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string en_BSBI_ABOUT {
            get {
                return ResourceManager.GetString("en_BSBI_ABOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        internal static string en_BSBI_ACCOUNT {
            get {
                return ResourceManager.GetString("en_BSBI_ACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BoardStatus.
        /// </summary>
        internal static string en_BSBI_BOARDSTATUS {
            get {
                return ResourceManager.GetString("en_BSBI_BOARDSTATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CameraStatus.
        /// </summary>
        internal static string en_BSBI_CAMERASTATUS {
            get {
                return ResourceManager.GetString("en_BSBI_CAMERASTATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Routine.
        /// </summary>
        internal static string en_BSBI_ROUTINE {
            get {
                return ResourceManager.GetString("en_BSBI_ROUTINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SerialPortStatus.
        /// </summary>
        internal static string en_BSBI_SERIALPORTSTATUS {
            get {
                return ResourceManager.GetString("en_BSBI_SERIALPORTSTATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set.
        /// </summary>
        internal static string en_BSBI_SET {
            get {
                return ResourceManager.GetString("en_BSBI_SET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;&gt;.
        /// </summary>
        internal static string en_BSTI_CLIENTNAME {
            get {
                return ResourceManager.GetString("en_BSTI_CLIENTNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CurrentAccount:.
        /// </summary>
        internal static string en_BSTI_CURRENTACCOUNT {
            get {
                return ResourceManager.GetString("en_BSTI_CURRENTACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CurrentTime:.
        /// </summary>
        internal static string en_BSTI_CURRENTTIME {
            get {
                return ResourceManager.GetString("en_BSTI_CURRENTTIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dialog for new routine.
        /// </summary>
        internal static string en_FRM_NEWROUTINE {
            get {
                return ResourceManager.GetString("en_FRM_NEWROUTINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dialog for routine manager.
        /// </summary>
        internal static string en_FRM_ROUTINEMANAGER {
            get {
                return ResourceManager.GetString("en_FRM_ROUTINEMANAGER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set routine parameter.
        /// </summary>
        internal static string en_FRM_SETROUTINEPARA {
            get {
                return ResourceManager.GetString("en_FRM_SETROUTINEPARA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ElpsT:.
        /// </summary>
        internal static string en_LBLC_ELAPSETIME {
            get {
                return ResourceManager.GetString("en_LBLC_ELAPSETIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter new routine name:.
        /// </summary>
        internal static string en_LBLC_PROMPTNEWROUTINENAME {
            get {
                return ResourceManager.GetString("en_LBLC_PROMPTNEWROUTINENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProNG:.
        /// </summary>
        internal static string en_LBLC_PRONG {
            get {
                return ResourceManager.GetString("en_LBLC_PRONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProOK:.
        /// </summary>
        internal static string en_LBLC_PROOK {
            get {
                return ResourceManager.GetString("en_LBLC_PROOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YldRto:.
        /// </summary>
        internal static string en_LBLC_PROYIELDRATIO {
            get {
                return ResourceManager.GetString("en_LBLC_PROYIELDRATIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STOP.
        /// </summary>
        internal static string en_LBLC_RUNSTATE {
            get {
                return ResourceManager.GetString("en_LBLC_RUNSTATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by name:.
        /// </summary>
        internal static string en_LBLC_SEARCHBYNAMES {
            get {
                return ResourceManager.GetString("en_LBLC_SEARCHBYNAMES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OFF.
        /// </summary>
        internal static string en_OFFLINE {
            get {
                return ResourceManager.GetString("en_OFFLINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ON.
        /// </summary>
        internal static string en_ONLINE {
            get {
                return ResourceManager.GetString("en_ONLINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string en_SBTN_CANCEL {
            get {
                return ResourceManager.GetString("en_SBTN_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string en_SBTN_CLEARROUTINE {
            get {
                return ResourceManager.GetString("en_SBTN_CLEARROUTINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string en_SBTN_CONFIRM {
            get {
                return ResourceManager.GetString("en_SBTN_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string en_SBTN_COUNTCLEAR {
            get {
                return ResourceManager.GetString("en_SBTN_COUNTCLEAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string en_SBTN_DELETEROUTINE {
            get {
                return ResourceManager.GetString("en_SBTN_DELETEROUTINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string en_SBTN_EDITROUTINE {
            get {
                return ResourceManager.GetString("en_SBTN_EDITROUTINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string en_SBTN_EXIT {
            get {
                return ResourceManager.GetString("en_SBTN_EXIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        internal static string en_SBTN_LOADROUTINE {
            get {
                return ResourceManager.GetString("en_SBTN_LOADROUTINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string en_SBTN_NEWROUTINE {
            get {
                return ResourceManager.GetString("en_SBTN_NEWROUTINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string en_SBTN_SEARCH {
            get {
                return ResourceManager.GetString("en_SBTN_SEARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hzzh-kj Co.,Ltd.
        /// </summary>
        internal static string en_VENDORINFO {
            get {
                return ResourceManager.GetString("en_VENDORINFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] halcondotnet {
            get {
                object obj = ResourceManager.GetObject("halcondotnet", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
