//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProCommon.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProCommon.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 闭合圆环.
        /// </summary>
        internal static string chs_BBI_ANNULUS {
            get {
                return ResourceManager.GetString("chs_BBI_ANNULUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 闭合圆形.
        /// </summary>
        internal static string chs_BBI_CIRCLE {
            get {
                return ResourceManager.GetString("chs_BBI_CIRCLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 有向圆弧.
        /// </summary>
        internal static string chs_BBI_CIRCULARARC {
            get {
                return ResourceManager.GetString("chs_BBI_CIRCULARARC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 清空图形.
        /// </summary>
        internal static string chs_BBI_CLEARICONIC {
            get {
                return ResourceManager.GetString("chs_BBI_CLEARICONIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除活动ROI.
        /// </summary>
        internal static string chs_BBI_DELETEACTIVEROI {
            get {
                return ResourceManager.GetString("chs_BBI_DELETEACTIVEROI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除所有ROI.
        /// </summary>
        internal static string chs_BBI_DELETEALLROI {
            get {
                return ResourceManager.GetString("chs_BBI_DELETEALLROI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 矢量线段.
        /// </summary>
        internal static string chs_BBI_LINE {
            get {
                return ResourceManager.GetString("chs_BBI_LINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 加载图像.
        /// </summary>
        internal static string chs_BBI_LOADIMAGE {
            get {
                return ResourceManager.GetString("chs_BBI_LOADIMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 齐轴矩形.
        /// </summary>
        internal static string chs_BBI_RECTANGLE1 {
            get {
                return ResourceManager.GetString("chs_BBI_RECTANGLE1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 仿射矩形.
        /// </summary>
        internal static string chs_BBI_RECTANGLE2 {
            get {
                return ResourceManager.GetString("chs_BBI_RECTANGLE2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重置窗体.
        /// </summary>
        internal static string chs_BBI_RESETWINDOW {
            get {
                return ResourceManager.GetString("chs_BBI_RESETWINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新区域.
        /// </summary>
        internal static string chs_BBI_UPDATEREGION {
            get {
                return ResourceManager.GetString("chs_BBI_UPDATEREGION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 局部放大.
        /// </summary>
        internal static string chs_BCHKI_MAGNIFY {
            get {
                return ResourceManager.GetString("chs_BCHKI_MAGNIFY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 修改区域.
        /// </summary>
        internal static string chs_BCHKI_MODIFYREGION {
            get {
                return ResourceManager.GetString("chs_BCHKI_MODIFYREGION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 移动图形.
        /// </summary>
        internal static string chs_BCHKI_MOVE {
            get {
                return ResourceManager.GetString("chs_BCHKI_MOVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无操作.
        /// </summary>
        internal static string chs_BCHKI_NONE {
            get {
                return ResourceManager.GetString("chs_BCHKI_NONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 缩放图形.
        /// </summary>
        internal static string chs_BCHKI_ZOOM {
            get {
                return ResourceManager.GetString("chs_BCHKI_ZOOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 定义与修改区域窗口.
        /// </summary>
        internal static string chs_FRM_DEFINEANDMODIFYREGION {
            get {
                return ResourceManager.GetString("chs_FRM_DEFINEANDMODIFYREGION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 账户登录对话框.
        /// </summary>
        internal static string chs_FRM_LOGIN {
            get {
                return ResourceManager.GetString("chs_FRM_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 账户管理对话框.
        /// </summary>
        internal static string chs_FRM_MANAGEACCOUNT {
            get {
                return ResourceManager.GetString("chs_FRM_MANAGEACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 账户详情.
        /// </summary>
        internal static string chs_GRPC_ACCOUNTDETAIL {
            get {
                return ResourceManager.GetString("chs_GRPC_ACCOUNTDETAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 账户信息.
        /// </summary>
        internal static string chs_GRPC_ACCOUNTPROMPT {
            get {
                return ResourceManager.GetString("chs_GRPC_ACCOUNTPROMPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 操作选项.
        /// </summary>
        internal static string chs_GRPC_OPERATIONOPTION {
            get {
                return ResourceManager.GetString("chs_GRPC_OPERATIONOPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 操作提示.
        /// </summary>
        internal static string chs_GRPC_OPERATIONPROMPT {
            get {
                return ResourceManager.GetString("chs_GRPC_OPERATIONPROMPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 权限:.
        /// </summary>
        internal static string chs_LBLC_ACCOUNTAUTHORITY {
            get {
                return ResourceManager.GetString("chs_LBLC_ACCOUNTAUTHORITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 列表:.
        /// </summary>
        internal static string chs_LBLC_ACCOUNTLIST {
            get {
                return ResourceManager.GetString("chs_LBLC_ACCOUNTLIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 名称:.
        /// </summary>
        internal static string chs_LBLC_ACCOUNTNAME {
            get {
                return ResourceManager.GetString("chs_LBLC_ACCOUNTNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 密码:.
        /// </summary>
        internal static string chs_LBLC_ACCOUNTPASSWORD {
            get {
                return ResourceManager.GetString("chs_LBLC_ACCOUNTPASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 账户:.
        /// </summary>
        internal static string chs_LBLC_ACCOUNTSELECTION {
            get {
                return ResourceManager.GetString("chs_LBLC_ACCOUNTSELECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 异常提示.
        /// </summary>
        internal static string chs_LBLC_ERRORPROMPT {
            get {
                return ResourceManager.GetString("chs_LBLC_ERRORPROMPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 密码:.
        /// </summary>
        internal static string chs_LBLC_PASSWORD {
            get {
                return ResourceManager.GetString("chs_LBLC_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新增.
        /// </summary>
        internal static string chs_RBTN_ADD {
            get {
                return ResourceManager.GetString("chs_RBTN_ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除.
        /// </summary>
        internal static string chs_RBTN_DELETE {
            get {
                return ResourceManager.GetString("chs_RBTN_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 修改.
        /// </summary>
        internal static string chs_RBTN_MODIFY {
            get {
                return ResourceManager.GetString("chs_RBTN_MODIFY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取消.
        /// </summary>
        internal static string chs_SBTN_CANCEL {
            get {
                return ResourceManager.GetString("chs_SBTN_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确认.
        /// </summary>
        internal static string chs_SBTN_CONFIRM {
            get {
                return ResourceManager.GetString("chs_SBTN_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 登录.
        /// </summary>
        internal static string chs_SBTN_LOGIN {
            get {
                return ResourceManager.GetString("chs_SBTN_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 一般权限.
        /// </summary>
        internal static string chs_XTABP_GENERALAUTHORITY {
            get {
                return ResourceManager.GetString("chs_XTABP_GENERALAUTHORITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 管理员权限.
        /// </summary>
        internal static string chs_XTABP_MANAGERAUTHORITY {
            get {
                return ResourceManager.GetString("chs_XTABP_MANAGERAUTHORITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annulus.
        /// </summary>
        internal static string en_BBI_ANNULUS {
            get {
                return ResourceManager.GetString("en_BBI_ANNULUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circle.
        /// </summary>
        internal static string en_BBI_CIRCLE {
            get {
                return ResourceManager.GetString("en_BBI_CIRCLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CircularArc.
        /// </summary>
        internal static string en_BBI_CIRCULARARC {
            get {
                return ResourceManager.GetString("en_BBI_CIRCULARARC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Iconic.
        /// </summary>
        internal static string en_BBI_CLEARICONIC {
            get {
                return ResourceManager.GetString("en_BBI_CLEARICONIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeleteActive.
        /// </summary>
        internal static string en_BBI_DELETEACTIVEROI {
            get {
                return ResourceManager.GetString("en_BBI_DELETEACTIVEROI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeleteAll.
        /// </summary>
        internal static string en_BBI_DELETEALLROI {
            get {
                return ResourceManager.GetString("en_BBI_DELETEALLROI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line.
        /// </summary>
        internal static string en_BBI_LINE {
            get {
                return ResourceManager.GetString("en_BBI_LINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Image.
        /// </summary>
        internal static string en_BBI_LOADIMAGE {
            get {
                return ResourceManager.GetString("en_BBI_LOADIMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rectangle1.
        /// </summary>
        internal static string en_BBI_RECTANGLE1 {
            get {
                return ResourceManager.GetString("en_BBI_RECTANGLE1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rectangle2.
        /// </summary>
        internal static string en_BBI_RECTANGLE2 {
            get {
                return ResourceManager.GetString("en_BBI_RECTANGLE2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ResetWindow.
        /// </summary>
        internal static string en_BBI_RESETWINDOW {
            get {
                return ResourceManager.GetString("en_BBI_RESETWINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Region.
        /// </summary>
        internal static string en_BBI_UPDATEREGION {
            get {
                return ResourceManager.GetString("en_BBI_UPDATEREGION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magnify.
        /// </summary>
        internal static string en_BCHKI_MAGNIFY {
            get {
                return ResourceManager.GetString("en_BCHKI_MAGNIFY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify Region.
        /// </summary>
        internal static string en_BCHKI_MODIFYREGION {
            get {
                return ResourceManager.GetString("en_BCHKI_MODIFYREGION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move.
        /// </summary>
        internal static string en_BCHKI_MOVE {
            get {
                return ResourceManager.GetString("en_BCHKI_MOVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string en_BCHKI_NONE {
            get {
                return ResourceManager.GetString("en_BCHKI_NONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom.
        /// </summary>
        internal static string en_BCHKI_ZOOM {
            get {
                return ResourceManager.GetString("en_BCHKI_ZOOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define and modify region.
        /// </summary>
        internal static string en_FRM_DEFINEANDMODIFYREGION {
            get {
                return ResourceManager.GetString("en_FRM_DEFINEANDMODIFYREGION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dialog for login.
        /// </summary>
        internal static string en_FRM_LOGIN {
            get {
                return ResourceManager.GetString("en_FRM_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dialog for account managing .
        /// </summary>
        internal static string en_FRM_MANAGEACCOUNT {
            get {
                return ResourceManager.GetString("en_FRM_MANAGEACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Detail.
        /// </summary>
        internal static string en_GRPC_ACCOUNTDETAIL {
            get {
                return ResourceManager.GetString("en_GRPC_ACCOUNTDETAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AccPrompt.
        /// </summary>
        internal static string en_GRPC_ACCOUNTPROMPT {
            get {
                return ResourceManager.GetString("en_GRPC_ACCOUNTPROMPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OperationOption.
        /// </summary>
        internal static string en_GRPC_OPERATIONOPTION {
            get {
                return ResourceManager.GetString("en_GRPC_OPERATIONOPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OperationPrompt.
        /// </summary>
        internal static string en_GRPC_OPERATIONPROMPT {
            get {
                return ResourceManager.GetString("en_GRPC_OPERATIONPROMPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authority:.
        /// </summary>
        internal static string en_LBLC_ACCOUNTAUTHORITY {
            get {
                return ResourceManager.GetString("en_LBLC_ACCOUNTAUTHORITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List:.
        /// </summary>
        internal static string en_LBLC_ACCOUNTLIST {
            get {
                return ResourceManager.GetString("en_LBLC_ACCOUNTLIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        internal static string en_LBLC_ACCOUNTNAME {
            get {
                return ResourceManager.GetString("en_LBLC_ACCOUNTNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PassWorld:.
        /// </summary>
        internal static string en_LBLC_ACCOUNTPASSWORD {
            get {
                return ResourceManager.GetString("en_LBLC_ACCOUNTPASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account:.
        /// </summary>
        internal static string en_LBLC_ACCOUNTSELECTION {
            get {
                return ResourceManager.GetString("en_LBLC_ACCOUNTSELECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ErrorPrompt.
        /// </summary>
        internal static string en_LBLC_ERRORPROMPT {
            get {
                return ResourceManager.GetString("en_LBLC_ERRORPROMPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PassWord:.
        /// </summary>
        internal static string en_LBLC_PASSWORD {
            get {
                return ResourceManager.GetString("en_LBLC_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string en_RBTN_ADD {
            get {
                return ResourceManager.GetString("en_RBTN_ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string en_RBTN_DELETE {
            get {
                return ResourceManager.GetString("en_RBTN_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify.
        /// </summary>
        internal static string en_RBTN_MODIFY {
            get {
                return ResourceManager.GetString("en_RBTN_MODIFY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string en_SBTN_CANCEL {
            get {
                return ResourceManager.GetString("en_SBTN_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string en_SBTN_CONFIRM {
            get {
                return ResourceManager.GetString("en_SBTN_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string en_SBTN_LOGIN {
            get {
                return ResourceManager.GetString("en_SBTN_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Authority.
        /// </summary>
        internal static string en_XTABP_GENERALAUTHORITY {
            get {
                return ResourceManager.GetString("en_XTABP_GENERALAUTHORITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager Authority.
        /// </summary>
        internal static string en_XTABP_MANAGERAUTHORITY {
            get {
                return ResourceManager.GetString("en_XTABP_MANAGERAUTHORITY", resourceCulture);
            }
        }
    }
}
